### ISSUE TITLE
How to add this to Alfred 4? Complete newbie

### ISSUE THREAD

**Issue by AristoSocrates** [mattstein/alfred-datespan#1]
Hi there,
This isn't an issue per se, just me being completely clueless with this... how do I add this to Alfred so I can use it as a workflow? 
Thanks

**Comment by mattstein** [comment]
Hi @AristoSocrates! You can zip up the contents of this repository and change the filename’s `.zip` → `.alfredworkflow` and then double-click that file to install it. There’s also a link to a zip package on the old [blog post](https://workingconcept.com/blog/date-span-alfred-workflow): https://assets.workingconcept.com/blog/DateSpan.alfredworkflow.zip

I’m amazed this thing still works despite it being a one-commit wonder from seven years ago! Thanks for popping by. :)

**Comment by bosconb** [comment]
not work for alfred 5 , sir

**Comment by mattstein** [comment]
Hey @bosconb, I just upgraded to Alfred 5 and confirmed the current version of this workflow is still functional.

Can you download a .zip file of the current version, rename `.zip` to `.alfredworkflow`, install that and let me know if that works for you?

You can grab a .zip archive from [this repository’s landing page](https://github.com/mattstein/alfred-datespan):

![Screen Shot 2022-08-08 at 08 36 53 AM@2x](https://user-images.githubusercontent.com/2488775/183456998-db414a9c-9704-4d34-8154-7903812dc51a.png)

**Comment by mattstein** [comment]
If that doesn’t work, please let me know what happens and what’s not working so I can look into it!
